# Generated by Django 4.1.3 on 2022-11-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.priority')),
            ],
        ),
    ]
